# Site settings
baseURL = "/"
languageCode = "en-us"
title = "Alex Knows Data"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Alexander Kruse"
  description = "My portfolio of data driven projects"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicoo.png"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "AKD"
    subtitle = "Alex Knows Data"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    #[[params.navigation.links]]
    #  name = ""
    #  url = "blogs"

    [[params.navigation.links]]
      name = "About"
      url = "post/about"

    #[[params.navigation.links]]
    #  name = "Elements"
    #  url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
    #  name = "Get Started"
    #  url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
    #  name = "Log In"
    #  url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Alex."
    subtitle = "I do data analysis and visualizations."
    buttonText = "My Portfolio"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Data journalism with Spiegel Online"
      subtitle = "Projects I have worked on during my Google Fellowship with Spiegel Online"
      image = "schufa.png"
      url = "post/ddj"


    [[params.tiles.showcase]]
      title = "#nr18 Twitter Analysis"
      subtitle = "Twitter analysis of Netzwerk Recherche’s annual conference 2018"
      image = "people.png"
      url = "post/nr18"
        
    [[params.tiles.showcase]]
      title = "Hamburg Marathon 2018"
      subtitle = "Animated visualization of the Hamburg Marathon 2018"
      image = "marathon.jpg"
      url = "post/marathon-hamburg"
      
    [[params.tiles.showcase]]
      title = "Bike Sharing Hamburg"
      subtitle = "Interactive map of bike sharing in Hamburg"
      image = "bike_usage_HH.png"
      url = "post/stadtrad"
    
    [[params.tiles.showcase]]
      title = "#airrohr"
      subtitle = "Animated visualizations to show the current state of the airrohr project."
      image = "airrohr.jpg"
      url = "post/airrohr"
      
    [[params.tiles.showcase]]
      title = "Street Trees in Hamburg"
      subtitle = "Animated visualization of street tree plantings in Hamburg"
      image = "streettree.jpg"
      url = "post/streettree"
      
    [[params.tiles.showcase]]
      title = "Kaggle Solution: Yummly"
      subtitle = "Predict the category of a dish’s cuisine given a list of its ingredients"
      image = "kaggle.png"
      url = "post/yummly"
      
    [[params.tiles.showcase]]
      title = "Cluster Analysis"
      subtitle = "How to visualize the Results of a Cluster Analysis?"
      image = "clustering_small.JPG"
      url = "post/clustering"
      
    [[params.tiles.showcase]]
      title = "Coding Dürer Twitter Analysis"
      subtitle = "Twitter Analysis of a cultural hackathon"
      image = "twitter_result.jpg"
      url = "post/twitter"
    
    [[params.tiles.showcase]]
      title = "Coding Dürer"
      subtitle = "Interactive Map for a cultural hackathon"
      image = "codingdurer_screenshot.jpg"
      url = "post/coding-dürer"
      
    [[params.tiles.showcase]]
      title = "Building a recommendation engine in R"
      subtitle = "How to find similar products based on user histories?"
      #image = "attribution01_small.png"
      url = "post/reco-engine"
   
   [[params.tiles.showcase]]
      title = "Marketing Attribution Modeling"
      subtitle = "How to set up an algorithmic attribution model?"
      image = "attribution01_small.png"
      url = "post/attribution"

    [[params.tiles.showcase]]
      title = "Google Takeout"
      subtitle = "My R-related Google Search History over time "
      image = "takeout.jpg"
      url = "post/takeout"
      
    [[params.tiles.showcase]]
      title = "Kaggle Solution: OTTO"
      subtitle = "Top 16% Solution to Kaggle’s Product Classification Challenge"
      image = "kaggle.png"
      url = "post/kaggle"
      
    [[params.tiles.showcase]]
      title = "Coding Da Vinci"
      subtitle = "Interactive Map for a cultural hackathon"
      image = "cdv.jpg"
      url = "post/cdv"
    
    [[params.tiles.showcase]]
      title = "Simple but nifty cohorts in R"
      subtitle = "How to use ggplot to create cohorts?"
      image = "cohort_small.png"
      url = "post/cohorts"
      


  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Footer section
  [params.footer]
    enable = true
    copyright = "alexknowsdata"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com/krusealex2013"
      label = "Twitter"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/kruse-alex"
      label = "GitHub"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
